# Adaptive Data Filter Configuration
# Market condition-based filtering for AI/ML models

# Market condition scanning settings
market_scanning:
  scan_interval: 120  # 2 minutes in seconds
  condition_memory: 600  # 10 minutes of history
  smooth_transitions: true
  
  # Market condition thresholds
  thresholds:
    vix_high: 25
    vix_low: 15
    spy_bull_threshold: 0.005  # 0.5% move in 2 minutes
    spy_bear_threshold: -0.005  # -0.5% move in 2 minutes
    volume_high: 1.5  # 1.5x average volume

# Market condition specific filtering rules
market_conditions:
  bull_trending:
    description: "Strong upward market movement with low fear"
    triggers:
      - "spy_2min_change > 0.005"
      - "vix < 15"
    
    filter_rules:
      min_price: 20
      max_price: 500
      min_volume: 2000000
      min_market_cap: 1000000000  # $1B
      focus_sectors: 
        - "tech"
        - "growth"
        - "consumer_discretionary"
      min_momentum: 0.02
      max_beta: 2.0
    
    ml_strategy:
      strategy_name: "momentum_breakouts"
      min_score: 0.6
      max_candidates: 100
      features_focus:
        - "momentum"
        - "volume_surge"
        - "breakout_patterns"

  bear_trending:
    description: "Downward market movement or defensive positioning"
    triggers:
      - "spy_2min_change < -0.005"
    
    filter_rules:
      min_price: 15
      max_price: 300
      min_volume: 5000000  # Higher volume in bear markets
      min_market_cap: 500000000  # $500M
      focus_sectors:
        - "defensive"
        - "utilities"
        - "staples"
      max_beta: 0.8
      min_short_interest: 0.1
    
    ml_strategy:
      strategy_name: "short_setups"
      min_score: 0.6
      max_candidates: 50
      features_focus:
        - "weakness"
        - "failed_bounces"
        - "overvaluation"

  volatile:
    description: "High volatility market with elevated VIX"
    triggers:
      - "vix > 25"
    
    filter_rules:
      min_price: 25
      max_price: 400
      min_volume: 10000000  # Very high volume for volatile markets
      min_market_cap: 2000000000  # $2B
      focus_sectors:
        - "any"
      min_volatility: 0.03
      min_options_volume: 1000
    
    ml_strategy:
      strategy_name: "volatility_trades"
      min_score: 0.7
      max_candidates: 75
      features_focus:
        - "high_iv"
        - "news_reactive"
        - "options_flow"

  calm_range:
    description: "Normal market conditions with balanced approach"
    triggers:
      - "default_condition"
    
    filter_rules:
      min_price: 15
      max_price: 300
      min_volume: 1000000
      min_market_cap: 500000000  # $500M
      focus_sectors:
        - "any"
      balanced_criteria: true
    
    ml_strategy:
      strategy_name: "mean_reversion"
      min_score: 0.5
      max_candidates: 80
      features_focus:
        - "oversold"
        - "support_levels"
        - "value"

# Performance targets and monitoring
performance:
  targets:
    condition_scan: 5      # ms (every 2 minutes)
    stage1_filter: 20      # ms
    stage2_ml_prep: 50     # ms
    total_filter: 75       # ms (leaving 125ms for ML processing)
  
  monitoring:
    log_condition_changes: true
    log_filter_stats: true
    alert_slow_processing: true
    slow_threshold: 100    # ms

# Quality controls
quality_controls:
  min_candidates_per_condition: 10
  max_candidates_per_condition: 150
  
  # Data validation
  validation:
    require_price: true
    require_volume: true
    require_market_cap: true
    max_price: 1000  # Reject prices > $1000 (likely errors)
    min_price: 1     # Reject prices < $1 (penny stocks)

# Sector mappings for focus filtering
sector_mappings:
  tech:
    - "XLK"
    - "QQQ"
    - "AAPL"
    - "MSFT"
    - "NVDA"
    - "GOOGL"
    - "META"
  
  growth:
    - "ARKK"
    - "PLTR"
    - "TSLA"
    - "CRWD"
    - "SNOW"
  
  defensive:
    - "XLU"
    - "XLP"
    - "VZ"
    - "PG"
    - "JNJ"
  
  utilities:
    - "XLU"
    - "NEE"
    - "DUK"
    - "SO"
  
  staples:
    - "XLP"
    - "WMT"
    - "PG"
    - "KO"
    - "PEP"

# Integration settings
integration:
  polygon_websocket: true
  alpaca_execution: true
  ml_pipeline: true
  
  # Data flow settings
  batch_size: 1000
  processing_interval: 1  # seconds
  buffer_size: 5000

# Logging configuration
logging:
  level: "INFO"
  components:
    market_scanner: "INFO"
    stock_filter: "INFO"
    ml_filter: "INFO"
    performance: "DEBUG"
  
  # What to log
  log_events:
    condition_changes: true
    filter_results: true
    performance_metrics: true
    errors: true

# Entry Timing Configuration
entry_timing:
  optimal_windows:
    - name: "morning_momentum"
      start_time: "10:00"
      end_time: "10:30"
      expected_win_rate: 0.75
      description: "Post-opening range establishment"
    - name: "afternoon_initiation"
      start_time: "14:00"
      end_time: "14:30"
      expected_win_rate: 0.70
      description: "Afternoon momentum initiation"
    - name: "end_day_acceleration"
      start_time: "15:30"
      end_time: "16:00"
      expected_win_rate: 0.80
      description: "End-of-day momentum acceleration"
  
  avoid_windows:
    - name: "market_open"
      start_time: "09:30"
      end_time: "10:00"
      reason: "Opening volatility and noise"
    - name: "lunch_lull"
      start_time: "11:30"
      end_time: "13:30"
      reason: "Low volume and momentum"

# Momentum Consistency Filter Configuration
momentum_filter:
  top_decile_threshold: 0.1  # Top 10%
  ranking_interval: 3600     # Update rankings every hour
  min_momentum_6m: 0.05      # Minimum 6-month momentum
  min_momentum_5m: 0.04      # Minimum 5-month momentum
  
  # Historical data settings
  historical_data:
    lookback_months: 6
    min_data_points: 120     # Minimum trading days
    exclude_recent_ipos: true
    min_market_cap: 1000000000  # $1B minimum

# VIX Position Scaling Configuration
vix_position_scaling:
  enabled: true
  
  # VIX regime thresholds
  thresholds:
    low_vix: 15      # Below this = low volatility
    high_vix: 25     # Above this = high volatility
  
  # Position limits by regime
  regimes:
    low:
      max_positions: 8
      position_size: 6250
      risk_level: "low"
    medium:
      max_positions: 6
      position_size: 8333
      risk_level: "medium"
    high:
      max_positions: 5
      position_size: 10000
      risk_level: "high"
  
  # Capital management
  capital_management:
    total_capital: 50000
    max_position_pct: 20     # Max 20% per position
    reserve_cash_pct: 10     # Keep 10% cash reserve