# ML Models Configuration for reg3n Trading System
# Configuration for machine learning models, feature engineering, and model serving

# Model Server Configuration
model_server:
  host: "localhost"
  port: 8080
  workers: 4
  timeout: 30
  max_batch_size: 1000
  model_cache_size: 5  # Number of models to keep in memory
  
# Feature Engineering Configuration
feature_engineering:
  enabled: true
  
  # Technical Indicators
  technical_indicators:
    sma_periods: [5, 10, 20, 50, 200]
    ema_periods: [12, 26]
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    bollinger_period: 20
    bollinger_std: 2
    atr_period: 14
    
  # Price Features
  price_features:
    returns_periods: [1, 5, 10, 20]
    volatility_periods: [5, 10, 20]
    price_ratios: ["high_low", "close_open", "volume_sma"]
    
  # Volume Features
  volume_features:
    volume_sma_periods: [5, 10, 20]
    volume_ratios: true
    volume_price_trend: true
    
  # Market Context Features
  market_context:
    sector_relative_strength: true
    market_beta: true
    correlation_spy: true
    vix_ratio: true
    
  # Cross-Asset Signals
  cross_asset:
    bond_yield_correlation: true
    dollar_strength: true
    commodity_signals: true

# Ensemble Manager Configuration
ensemble:
  enabled: true
  models:
    - name: "momentum_model"
      weight: 0.3
      type: "xgboost"
      features: ["momentum", "volume", "technical"]
      
    - name: "mean_reversion_model"
      weight: 0.25
      type: "lightgbm"
      features: ["oversold", "support_resistance", "value"]
      
    - name: "volatility_model"
      weight: 0.2
      type: "neural_network"
      features: ["volatility", "options_flow", "news_sentiment"]
      
    - name: "trend_following_model"
      weight: 0.25
      type: "random_forest"
      features: ["trend", "breakout", "momentum"]
  
  # Ensemble Strategy
  combination_method: "weighted_average"  # weighted_average, voting, stacking
  confidence_threshold: 0.6
  min_models_agreement: 2
  
# Online Learning Configuration
online_learning:
  enabled: true
  update_frequency: "daily"  # hourly, daily, weekly
  learning_rate: 0.01
  batch_size: 1000
  memory_window: 252  # Trading days to remember
  
  # Adaptive Learning
  performance_tracking: true
  model_decay_factor: 0.95
  retraining_threshold: 0.1  # Retrain if performance drops by 10%
  
# Model Training Configuration
training:
  # Data Splits
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15
  
  # Cross Validation
  cv_folds: 5
  time_series_split: true
  
  # Hyperparameter Optimization
  hyperopt:
    enabled: true
    max_evals: 100
    algorithm: "tpe"  # tpe, random, anneal
    
  # Early Stopping
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

# Model Performance Monitoring
monitoring:
  enabled: true
  
  # Performance Metrics
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"
    - "sharpe_ratio"
    - "max_drawdown"
    
  # Drift Detection
  drift_detection:
    enabled: true
    method: "ks_test"  # ks_test, psi, wasserstein
    threshold: 0.05
    window_size: 1000
    
  # Alerts
  alerts:
    performance_degradation: true
    data_drift: true
    model_errors: true

# Data Processing Configuration
data_processing:
  # Feature Scaling
  scaling:
    method: "robust"  # standard, minmax, robust, quantile
    feature_range: [-1, 1]
    
  # Missing Data Handling
  missing_data:
    strategy: "forward_fill"  # forward_fill, interpolate, drop, median
    max_missing_ratio: 0.1
    
  # Outlier Detection
  outlier_detection:
    enabled: true
    method: "isolation_forest"  # isolation_forest, local_outlier_factor, one_class_svm
    contamination: 0.05

# Model Storage Configuration
storage:
  model_path: "./models"
  backup_enabled: true
  backup_frequency: "daily"
  max_model_versions: 10
  compression: true
  
# GPU Configuration
gpu:
  enabled: false  # Set to true if GPU available
  device_id: 0
  memory_fraction: 0.8
  
# Logging Configuration
logging:
  enabled: true
  level: "INFO"
  components:
    feature_engineering: true
    model_training: true
    model_serving: true
    ensemble_manager: true
    online_learning: true
    monitoring: true
    
# Performance Targets
performance:
  feature_extraction_ms: 50
  model_inference_ms: 10
  ensemble_prediction_ms: 25
  total_pipeline_ms: 100