# Utils Configuration for reg3n Trading System
# Configuration for utility functions, logging, debugging, and system operations

# System Logging Configuration
logging:
  enabled: true
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Log Formatting
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # File Logging
  file_logging:
    enabled: true
    log_file: "logs/system.log"
    max_file_size_mb: 100
    backup_count: 5
    rotation: true
    
  # Console Logging
  console_logging:
    enabled: true
    colored_output: true
    
  # Component-specific Logging Levels
  components:
    data_pipeline: "INFO"
    trading_pipeline: "INFO"
    ml_models: "INFO"
    filters: "INFO"
    utils: "INFO"
    tests: "DEBUG"
    
  # Structured Logging
  structured:
    enabled: true
    format: "json"  # json, key_value
    include_metadata: true
    
  # Log Filtering
  filters:
    exclude_patterns:
      - "heartbeat"
      - "ping"
    include_only: []

# Debug Configuration for reg3n Trading System
# Centralized debugging controls for all components
debug:
  enabled: true  # Master switch to enable/disable all debugging
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Component-specific debug levels
  components:
    data_pipeline: "DEBUG"
    trading_pipeline: "DEBUG"
    ml_models: "DEBUG"
    filters: "DEBUG"
    utils: "INFO"
    tests: "DEBUG"
    system: "INFO"
    
    # Sub-component specific controls
    polygon_websocket: "DEBUG"
    polygon_rest_api: "DEBUG"
    alpaca_websocket: "DEBUG"
    alpaca_rest_api: "DEBUG"
    model_server: "DEBUG"
    ensemble_manager: "DEBUG"
    online_learning: "DEBUG"
    momentum_execution: "DEBUG"
    kelly_position_sizer: "DEBUG"
    adaptive_data_filter: "DEBUG"
    momentum_consistency_filter: "DEBUG"
    vix_position_scaler: "DEBUG"
    entry_timing_optimizer: "DEBUG"

# Deep Debugging Features
deep_debugging:
  enabled: true
  
  # Function entry/exit tracing
  function_tracing:
    enabled: true
    include_args: true
    include_return_values: true
    max_arg_length: 200
    
  # Performance debugging
  performance_tracking:
    enabled: true
    log_slow_functions: true
    slow_function_threshold_ms: 100
    track_memory_usage: true
    
  # Data flow debugging
  data_flow:
    enabled: true
    log_data_transformations: true
    log_api_requests: true
    log_api_responses: true
    max_data_log_length: 500
    
  # Error debugging
  error_debugging:
    enabled: true
    include_stack_traces: true
    include_local_variables: true
    log_error_context: true
    
  # Trading specific debugging
  trading_debug:
    enabled: true
    log_signal_processing: true
    log_position_calculations: true
    log_order_submissions: true
    log_risk_calculations: true
    log_filter_decisions: true
    
  # ML Model debugging
  ml_debug:
    enabled: true
    log_feature_engineering: true
    log_model_predictions: true
    log_ensemble_decisions: true
    log_online_learning: true
    log_performance_metrics: true

# Debug Output Configuration
debug_output:
  # Console debugging
  console:
    enabled: true
    colored_output: true
    include_timestamps: true
    include_thread_info: true
    include_function_names: true
    
  # File debugging
  file:
    enabled: true
    separate_debug_file: true
    debug_file_path: "logs/debug.log"
    max_file_size_mb: 500
    backup_count: 10
    
  # Real-time debugging
  realtime:
    enabled: false  # Enable for live debugging sessions
    websocket_port: 8765
    max_connections: 5

# Debug Filters
debug_filters:
  # Exclude noisy debug messages
  exclude_patterns:
    - "heartbeat"
    - "ping"
    - "connection_alive"
    
  # Include only specific patterns (empty = include all)
  include_only_patterns: []
  
  # Symbol-specific debugging
  symbol_filter:
    enabled: false
    symbols: ["AAPL", "MSFT", "TSLA"]  # Only debug these symbols
    
  # Time-based filtering
  time_filter:
    enabled: false
    start_time: "09:30:00"  # Market open
    end_time: "16:00:00"    # Market close

# Debug Sampling (to reduce log volume)
debug_sampling:
  enabled: false
  sample_rate: 0.1  # Log 10% of debug messages
  always_log_errors: true
  always_log_warnings: true

# Debug Metrics
debug_metrics:
  enabled: true
  track_debug_volume: true
  track_performance_impact: true
  report_interval_minutes: 5

# Emergency Debug Controls
emergency_debug:
  # Panic mode - minimal logging for performance
  panic_mode:
    enabled: false
    log_level: "ERROR"
    disable_deep_debugging: true
    
  # Debug storm protection
  storm_protection:
    enabled: true
    max_messages_per_second: 100
    cooldown_period_seconds: 10
    
# Performance Monitoring
performance:
  enabled: true
  
  # Metrics Collection
  metrics:
    system_metrics: true
    application_metrics: true
    custom_metrics: true
    
  # System Monitoring
  system:
    cpu_usage: true
    memory_usage: true
    disk_usage: true
    network_io: true
    
  # Application Monitoring
  application:
    request_latency: true
    throughput: true
    error_rates: true
    queue_sizes: true
    
  # Alerting
  alerts:
    enabled: true
    cpu_threshold: 80  # Percent
    memory_threshold: 85  # Percent
    disk_threshold: 90  # Percent
    error_rate_threshold: 5  # Percent
    
# Error Handling
error_handling:
  enabled: true
  
  # Retry Configuration
  retry:
    max_attempts: 3
    backoff_strategy: "exponential"  # linear, exponential, fixed
    base_delay: 1.0  # seconds
    max_delay: 60.0  # seconds
    jitter: true
    
  # Circuit Breaker
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30  # seconds
    half_open_max_calls: 3
    
  # Error Notifications
  notifications:
    enabled: true
    channels: ["log", "email"]  # log, email, slack, webhook
    severity_threshold: "ERROR"
    
# Data Validation
validation:
  enabled: true
  
  # Schema Validation
  schema:
    strict_mode: false
    allow_unknown: true
    coerce_types: true
    
  # Data Quality Checks
  quality_checks:
    null_value_threshold: 0.1  # 10% max null values
    duplicate_threshold: 0.05  # 5% max duplicates
    outlier_detection: true
    
# Caching Configuration
caching:
  enabled: true
  
  # Cache Backend
  backend: "memory"  # memory, redis, memcached
  
  # Memory Cache
  memory:
    max_size_mb: 512
    ttl_seconds: 3600  # 1 hour
    cleanup_interval: 300  # 5 minutes
    
  # Redis Cache (if backend is redis)
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: null
    ssl: false
    
# Database Configuration
database:
  # Connection Pool
  pool:
    min_connections: 5
    max_connections: 20
    connection_timeout: 30
    idle_timeout: 300
    
  # Query Optimization
  query:
    timeout: 30
    retry_attempts: 3
    batch_size: 1000
    
# File Operations
file_operations:
  # Temporary Files
  temp_dir: "/tmp/reg3n"
  cleanup_temp_files: true
  temp_file_ttl: 3600  # 1 hour
  
  # File Compression
  compression:
    enabled: true
    algorithm: "gzip"  # gzip, bz2, lzma
    level: 6
    
  # File Backup
  backup:
    enabled: true
    backup_dir: "./backups"
    retention_days: 30
    
# Security Configuration
security:
  # API Keys
  api_keys:
    encryption: true
    rotation_days: 90
    
  # Data Encryption
  encryption:
    algorithm: "AES-256"
    key_derivation: "PBKDF2"
    
  # Access Control
  access_control:
    rate_limiting: true
    ip_whitelist: []
    
# Health Checks
health_checks:
  enabled: true
  interval: 30  # seconds
  timeout: 10  # seconds
  
  # Component Health
  components:
    - name: "database"
      check_type: "connection"
      critical: true
      
    - name: "external_apis"
      check_type: "http"
      critical: false
      
    - name: "file_system"
      check_type: "disk_space"
      critical: true
      
# Configuration Management
config:
  # Environment Variables
  env_vars:
    required:
      - "POLYGON_API_KEY"
      - "ALPACA_API_KEY"
      - "ALPACA_SECRET_KEY"
    optional:
      - "REDIS_URL"
      - "DATABASE_URL"
      
  # Configuration Validation
  validation:
    strict: false
    warn_missing: true
    
# Utilities
utilities:
  # Date/Time Utilities
  datetime:
    timezone: "America/New_York"
    market_hours:
      start: "09:30"
      end: "16:00"
      
  # Math Utilities
  math:
    precision: 8
    rounding_mode: "half_up"
    
  # String Utilities
  string:
    encoding: "utf-8"
    normalize: true